version: '3.3'
services:
  mysql-docker:
    platform: linux/x86_64
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: booking
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1
      MYSQL_ROOT_PASSWORD: admin1
    ports:
      - '23306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./data:/var/lib/mysql